// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqXJd_T129t_KVyACWGb-XiKWFemImfA',
    appId: '1:427710320418:web:0a677b370af64be9d09f7b',
    messagingSenderId: '427710320418',
    projectId: 'gaweeapp-backend-ac3a1',
    authDomain: 'gaweeapp-backend-ac3a1.firebaseapp.com',
    storageBucket: 'gaweeapp-backend-ac3a1.firebasestorage.app',
    measurementId: 'G-428W4RHBVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRv1uxc8CQA9XR9_Be5gHjRt4CBRCeUho',
    appId: '1:427710320418:android:d542a6b2560e1fdbd09f7b',
    messagingSenderId: '427710320418',
    projectId: 'gaweeapp-backend-ac3a1',
    storageBucket: 'gaweeapp-backend-ac3a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8mhlcqbgcB6r69CQibcSB1teiPQL4AvU',
    appId: '1:427710320418:ios:aabac94c32fc5872d09f7b',
    messagingSenderId: '427710320418',
    projectId: 'gaweeapp-backend-ac3a1',
    storageBucket: 'gaweeapp-backend-ac3a1.firebasestorage.app',
    androidClientId: '427710320418-g58fa9a7880e6c3ua0lkjvocrl97jktn.apps.googleusercontent.com',
    iosClientId: '427710320418-tekfaltg4ettmrfcmniq20eg4rl5dorv.apps.googleusercontent.com',
    iosBundleId: 'com.gaweapp.mobilewebser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8mhlcqbgcB6r69CQibcSB1teiPQL4AvU',
    appId: '1:427710320418:ios:ee6f29d32a7ba52dd09f7b',
    messagingSenderId: '427710320418',
    projectId: 'gaweeapp-backend-ac3a1',
    storageBucket: 'gaweeapp-backend-ac3a1.firebasestorage.app',
    androidClientId: '427710320418-g58fa9a7880e6c3ua0lkjvocrl97jktn.apps.googleusercontent.com',
    iosClientId: '427710320418-89k6es13b197qctgj0me8340ba4gh83m.apps.googleusercontent.com',
    iosBundleId: 'com.example.coba1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkqXJd_T129t_KVyACWGb-XiKWFemImfA',
    appId: '1:427710320418:web:1dff4643720f8f53d09f7b',
    messagingSenderId: '427710320418',
    projectId: 'gaweeapp-backend-ac3a1',
    authDomain: 'gaweeapp-backend-ac3a1.firebaseapp.com',
    storageBucket: 'gaweeapp-backend-ac3a1.firebasestorage.app',
    measurementId: 'G-PHRSH5Y0ZH',
  );
}
